version: "1.0"
info:
  model: int-scaffold
services:
- serviceName: testrestapi0.new_rad_.services:createPets
  packages:
  - name: TestradapiProject
    version: "1.0"
- serviceName: testrestapi0.new_rad_.services:listPets
  packages:
  - name: TestradapiProject
    version: "1.0"
- serviceName: testrestapi0.new_rad_.services:showPetById
  packages:
  - name: TestradapiProject
    version: "1.0"
